### ISSUE TITLE
Firefox portal detection crash

### ISSUE THREAD

**Issue by claunia** [tenox7/wrp#17]
If firefox is expecting WRP when it loads, crashes on first request:

```
claunia@zeus ~/Development/wrp $ ./wrp.py 
Web Rendering Proxy v1.4 serving at port: 8080
>>> URL request... http://detectportal.firefox.com/success.txt
127.0.0.1 - - [09/May/2017 01:02:42] "GET http://detectportal.firefox.com/success.txt HTTP/1.1" 200 -
Traceback (most recent call last):
  File "./wrp.py", line 424, in __main_qt
    image = renderer.render(WebkitRenderer.req_url)
  File "./wrp.py", line 132, in render
    image = helper.render(url)
  File "./wrp.py", line 242, in render
    % (WebkitRenderer.req_url, web_url))
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe
Aborted (core dumped)
```

**Comment by claunia** [comment]
Solved by #18
