### ISSUE TITLE
Character conversion problem

### ISSUE THREAD

**Issue by rakslice** [tenox7/wrp#24]
```
$ xvfb-run -s "-screen 0 1024x768x24" ./wrp.py
```
... snip ...
```
>>> URL request... http://main.system7today.com/softwareindex/productivity.html
10.0.2.2 - - [25/Jul/2018 17:07:19] "GET http://main.system7today.com/softwareindex/productivity.html HTTP/1.0" 200 -
Traceback (most recent call last):
  File "./wrp.py", line 446, in __main_qt
    image = renderer.render(WebkitRenderer.req_url)
  File "./wrp.py", line 146, in render
    image = helper.render(url)
  File "./wrp.py", line 287, in render
    % (xmin, ymin, xmax, ymax, turl, turl))
  File "/usr/lib/python2.7/socket.py", line 320, in write
    data = str(data) # XXX Should really reject non-string non-buffers
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 101: ordinal not in range(128)
Aborted
```
Running under Debian 9.5.

Potentially relevant env't vars:
```
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
TERM=xterm
```
Under these conditions on this system `sys.getdefaultencoding()` returns `"ascii"`.

Encoding the `unicode` before passing it to `httpout.write` at wrp.py:287 makes the error go away.

**Comment by tenox7** [comment]
thank you! please submit PR if you want
